version: "3.8"
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    build: .
    environment:
      - SHELL=/bin/bash
    depends_on:
      - mariadb
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe.rule=Host(`frap.web.musketeers.dev`)"
      - "traefik.http.services.frappe.loadbalancer.server.port=8000"
      - "traefik.http.routers.frappe.entrypoints=websecure"
      - "traefik.http.routers.frappe.tls=true"
      - "traefik.http.services.frappe.loadbalancer.server.scheme=http"   # 🧠 important line

volumes:
  mariadb-data:
