version: "3.8"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    build: .
    environment:
      - SHELL=/bin/bash
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - MARIADB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=123
      - SITE_NAME=frap.web.musketeers.dev
    depends_on:
      - mariadb
      - redis
    expose:
      - "8000"
      - "9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frappe.rule=Host(`frap.web.musketeers.dev`)"
      - "traefik.http.services.frappe.loadbalancer.server.port=8000"
      - "traefik.http.routers.frappe.entrypoints=websecure"
      - "traefik.http.routers.frappe.tls.certresolver=myresolver"
      # WebSocket fix
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.routers.frappe.middlewares=websocket"

  worker:
    build: .
    command: bench worker
    depends_on:
      - mariadb
      - redis
      - frappe

  scheduler:
    build: .
    command: bench schedule
    depends_on:
      - mariadb
      - redis
      - frappe

volumes:
  mariadb-data:
