version: "3.8"

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe
      MYSQL_DATABASE: frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always

  frappe:
    image: frappe/bench:latest
    restart: always
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
        if [ ! -d /home/frappe/frappe-bench/sites/hrms.localhost ]; then
          bench new-site --no-mariadb-socket --mariadb-root-password 123 --admin-password admin hrms.localhost &&
          bench --site hrms.localhost install-app hrms;
        fi &&
        bench start
      "
    environment:
      - SHELL=/bin/bash
      - MARIADB_HOST=mariadb
      - REDIS_CACHE=redis:6379
      - REDIS_QUEUE=redis:6379
      - REDIS_SOCKETIO=redis:6379
      - SITE_NAME=hrms.localhost
      - DB_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - ADMIN_PASSWORD=admin
      - INSTALL_APPS=hrms
    working_dir: /home/frappe
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8100:8000"
      - "9100:9000"

volumes:
  mariadb-data:
  sites:
